api:
  dashboard: true
  insecure: true

pilot:
  token: "ad5f61d8-a747-4300-b659-ac7d10a82573"

experimental:
  devPlugin:
    goPath: /plugins/go
    moduleName: github.com/darkweak/souin

log:
  level: DEBUG

accessLog: {}
